language: java
sudo: false

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - hiptest-publisher --config-file java-testng.conf --test-run-id 146353 --without=actionwords

script:
  - mvn package

after_script:
  - hiptest-publisher --config-file java-testng.conf --push "target/surefire-reports/junitreports/TEST-com.testng.coffeemachine.*.xml" --test-run-id 146353 --push-format junit
